### PR TITLE
Check for jdk undefined while looping through jdks array

### PR DESCRIPTION
**Pull request by mrzorn**
On my machine, for some reason there was an undefined value in the jdks array. The only way I could get everything to run locally for me was to add a check for undefined.

### CODE REVIEW

**Comment by mrzorn** [comment]
Signed the CLA - is there just some lag in that updating above?

**Comment by mrzorn** [comment]
Any reason this can't be merged in? I have this issue every time I update now and its quite a pain to have to fix.

**Comment by vlucas** [comment]
I submitted the same fix a different way for #126 and it looks like it just got approved. Maybe this will finally get merged?

**Comment by sgtcoolguy** [comment]
Closed in favor of #126

**Comment by mrzorn** [comment]
Only took over two and a half years for a response. Glad I don't even use titanium anymore.

**Pull request closed without merging**
